import React from "react";
import "./Privacy.css"; // Import the CSS file

import { Link } from "react-router-dom";
const PrivacyPolicy = () => {
  return (
    <>
      <div className="privacy-policy-container">
        <Link to="/">
          <button className="back-button">Back to Home</button>
        </Link>
        <div className="privacy-policy-content">
          <h1>Privacy Policy</h1>
          <p>
            This Privacy Policy explains how we collect, use, and protect the
            personal information of users of our website and services. Please
            read this policy carefully to understand how we handle your
            information. By accessing or using our website and services, you
            agree to the practices described in this Privacy Policy.
          </p>
          <p>
            **User Management** We collect and process personal information to
            differentiate users based on their roles: 1. **Admin**: An Admin
            user has access to all system features, can assign accounts to
            users, and has the authority to create and schedule content. 2.
            **Manager**: A Manager user can assign accounts to other users and
            has the ability to create and schedule content. 3. **User**: A User
            has the capability to create and schedule content.
          </p>
          <p>
            **Client Information Panel** We collect and store client details,
            which may include: - Name - Address - Email - Phone number - Social
            media URLs - Keywords - Access to Google Drive for specific clients
          </p>
          <p>
            **Content Creation** Our services allow for content creation by
            connecting to third-party services like Canva through APIs. When
            creating content, the data is processed and managed securely.
          </p>
          <p>
            **Chat GPT Access** We provide access to Chat GPT through an API.
            Any interactions with Chat GPT are logged and monitored for quality
            assurance and improvement.
          </p>
          <p>
            **Social Media Integration** Our services may integrate with various
            social media platforms, including Facebook, Instagram, LinkedIn,
            TikTok, Snapchat, and Google Maps, either through APIs or customer
            login access. Please review the privacy policies of these platforms
            for more information on data handling.
          </p>
          <p>
            **Calendar** We maintain a calendar for each client, displaying all
            scheduled social media content and specifying the platform on which
            it's scheduled to post. This information is stored securely.
          </p>
          <p>
            **Report Queries** We generate reports to provide insights into the
            content produced for clients. These reports may be generated by
            user, date, or platform. No personally identifiable information is
            disclosed in these reports.
          </p>
          <p>
            **Social Media Analytics** We collect social media analytics data
            for each client, including data by date and platform. This
            information is used to track the performance of content but does not
            include personal information.
          </p>
          <p>
            **AI Suggestions** We use AI to provide trending music, post ideas,
            and content suggestions. These suggestions are generated based on
            non-personalized data and user preferences.
          </p>
        </div>
      </div>
    </>
  );
};

export default PrivacyPolicy;
